JWock82/Pynite

- Examples/Double Beam - Point Load.py
- PyNite/FEModel3D.py
- PyNite/Member3D.py
I'm still trying to get my head around the maths of it, but:
1. A mechanism for orientating beams by specifying a reference point in the beam's ZX-plane.
2. Don't create the transformation matrix, T(), more than once.
3. I think T() needs to be transposed when transforming back to the global coordinate frame.
> End reaction fix + option for orienting beams

- PyNite/FEModel3D.py
When the Analyze methods encounter a singular stiffness matrix, it prints an error message and returns None. The program continues and crashes when trying to use the None value. Instead, this change raises an exception instead of returning, stopping analysis immediately and displaying the same error message.
Similarly, when the GetNode and related methods fail to find the element, an exception is raised instead of returning None.
Similarly, when the AddNodeLoads and related methods are passed an incorrect Direction argument, an exception is raised instead of doing nothing.
> Raise exception when stiffness matrix is singular, with error message

- Testing & Debugging/test_2D_frames.py
- Testing & Debugging/test_axial_load.py
- Testing & Debugging/test_benchmarks.py
- Testing & Debugging/test_end_releases.py
- Testing & Debugging/test_plates.py
- Testing & Debugging/test_springs.py
- Testing & Debugging/test_support_settlement.py
- Testing & Debugging/test_torsion.py
- Testing & Debugging/test_unstable_structure.py
I have converted 12 of the 13 test scripts into unittest.TestCases so that they can be run automatically. The test script titled `T Matrix Test` is not done yet. All plots and visualizations are removed.
The "correct" values are taken from the test scripts, if included in the source code, or else from the actual script output. Thus, naturally they all pass (with one exception, see below). These values should be reviewed for correctness.
For floating point results, the acceptable error is set to 0.5%. This value should be set to match the project's goals.
**Note**: Currently, one node of the support settlement test fails, due to a 7.5% difference from the expected value.
> Created test modules for the existing test scripts (12/13)

- PyNite/FEModel3D.py
Added an option to auto-name all model elements by leaving the 'name' field empty, avoiding the need to manually keep track of element names. This is especially useful for large models.
Also implemented duplicate name checks upon addition of model elements.
> Element auto-naming and duplicate checks

- Derivations/MITC4 Quad Element.ipynb
Fix typo in: PyNite/Derivations/MITC4 Quad Element.ipynb
Step 5
from:
As before, to obtain the $[B_m]$ matrix, we can substitute in the terms from the **follwing** expression into the expression for $[B_m]$:
to:
As before, to obtain the $[B_m]$ matrix, we can substitute in the terms from the **following** expression into the expression for $[B_m]$:
> fix typo in Derivations/MITC4 Quad Element.ipynb

- PyNite/Member3D.py
- PyNite/Visualization.py
I changed the check for `color_map` to check if the model has `Quads` or `Plates` directly. If the model does not have either `Quads` or `Plates` in it, rendering contours will fail with division by zero. This error occurs in `"Simple Beam - Point Load.py"` for example. I think this fix is clearer than checking `color_map` because it hits the root cause of the error. The `color_map` parameter is default=`None` in many places, which makes it easy to accidentally be set to `None`.
I also added a `ValueError` for the `Moment3D.moment` method, for invalid `Direction` arguments.
> Check for quads or plates before Rendering Contours.

- Examples/Beam on Elastic Foundation.py
- Examples/Braced Frame - Spring Supported.py
- Examples/Braced Frame - Tension Only.py
- Examples/Moment Frame - Lateral Load.py
- Examples/Rectangular Plate Bending - Qauds.py
- Examples/Rectangular Tank Wall - Hydrostatic Loads.py
- Examples/Shear Wall with Openings.py
- Examples/Simple Beam - Point Load.py
- Examples/Simple Beam - Uniform Load.py
- Examples/Space Frame - Nodal Loads 1.py
- Examples/Space Frame - Nodal Loads 2.py
- Examples/Space Truss - Nodal Load.py
- PyNite/Member3D.py
In the example scripts, it was references to `RenderModel` and the keyword change to `annotation_size`. In `Member3D`, there was an internal call to the deprecated `Shear` method.
> Updated the outdated method names and keyword parameters in the Examples scripts, and in Member3D.

- PyNite/FEModel3D.py
- PyNite/Member3D.py
- PyNite/Node3D.py
- PyNite/Plate3D.py
- PyNite/Spring3D.py
Current method iterates through all elements (members/springs/plates/quads) on every pass comparing nodes. 
In this pr, node usage is checked ahead of time to reduce runtime.
Tested with 50000 nodes and 200 elements and noted a substantially reduction in runtime (~45 sec to ~8 sec on my machine).
Also added a new method to the Node3D class (`Node3d.distance`) to calculate the distance to a secondary node.
> merge_duplicate_nodes speed-up

- Examples/Braced Frame - Repair Usage.py
- PyNite/FEModel3D.py
- PyNite/Member3D.py
1) Fixes [this](https://github.com/JWock82/PyNite/pull/125#issuecomment-1096798356).
I split up the `tolerance` kwarg in the `repair` method and set a maximum value for the tolerance in the `intersection_virtual` method to fix this issue.
2) Speeds up repair method by skipping duplicate vector calculations (these are expensive). 
Tested using 25-100 horizontal and 25-100 vertical members with good results; I was seeing 20-38% reduction in runtime.
3) Added some annotation in the `repair` method so it is easier to follow the logic. 
4) Change some naming.
> Speedup repair method

- PyNite/Report_Template.html
The reporting template does not work in its current state, since it is using the `member.Shear` and `member.Torsion` methods.
This PR updates the template to use `member.shear` and `member.torque` in place.
> Fix reporting template methods

- Examples/Simple Beam - Factored Envelope.py
- PyNite/Member3D.py
Addresses #144 with the following changes:
* Added an "array" method for `Member3D` for the following:
* `shear_array`
* `moment_array`
* `torque_array`
* `axial_array`
* `deflection_array`
* `rel_deflection_array`
* Added an `n_points` argument to the "plot" methods to allow for varying the resolution of the plot (added the argument as the final keyword argument to not break any existing code).
*  Added an example for the use case of plotting factored envelopes of varying number of points (Examples/"Simple Beam - Factored Envelope.py")
* Fixed bug in `Member3D.rel_deflection` where the actual `LoadCombo` object was being passed to `Member3D.d` instead of the combo name.
* Fixed various typos in doc strings of "plot" methods
> Results arrays (#144)

- PyNite/FEModel3D.py
I am using a significant set of load combinations for aerodynamic analysis (permutations of speed,rotation,angle) and I wanted a way to choose which to run running all of them takes about 15minutes.
I have added a `combos:list = None` keyword to each `analyze` function along wih appropriate documentation.
The analysis function now checks directly after the LoadCombos iteration if combos is specified the combo is in combos the case will proceed, otherwise continue is used to bypass unspecified combos
springs and member are activted for the combo in question or all if `combos` is None.
combos is also passed to `_check_static` and `_calc_reactions` so that only the run combos are checked.
I have run the testing suite on this and it appears fine. I haven't added any new tests.
> Allow Selective Analysis Of Load Combos

- PyNite/FEModel3D.py
Hi @JWock82,
I noticed that there were some breaking changes to the API with recent versions but that the updates were not applied to all of the methods in `FEModel3D`. I have updated the rest of the parameter names across the `FEModel3D` object by following what seemed to be the desired new convention. Here is how I understand it:
* When creating a new object (e.g. node, member, section, etc.), the method that creates it (e.g. `.add_node`) will accept a parameter called `name` to set the name of the object in the model.
* When creating an assignment to an existing object (e.g. a load to a member), then the parameter will be named something like `member_name` (as opposed to `Member`) to make it clear that this parameter is to accept a name and not a `Member` object itself.
I ran the test …
> Update parameter names in FEModel3D methods for consistency of API

- PyNite/Rendering.py
I tried running the new version to see the new PyVista display. It took some work. Once I got the installs figured out, I found that there seemed to be a bug in the function `sig_fig_round`. It was being passed a `text_label` and it was trying to perform math functions on the value. It seemed that a conversion step was necessary to convert the `text_label` to a `float`. 
I added the conversion into `sig_fig_round` and then the display worked. And...it looks nice! I love that it is not spawning a separate process that hangs your kernel like VTK does. Thank you!
> Added check and conversion for non-numerical data coming in to sig_fig_round

- Examples/Braced Frame - Tension Only.py
- Examples/Circular Bin with Conical Hopper.py
- Examples/Moment Frame - Lateral Load.py
- Examples/Rectangular Tank Wall - Hydrostatic Loads.py
- Examples/Space Frame - Nodal Loads 2.py
fix #228 
Thank you for providing the program, but I have found some bugs. I have submitted a Pull Request for your consideration. Here are detailed fixes.
- Fix method keyword args
- Fix `add_member_dist_load` and `add_node_load` method in `Braced Frame - Tension Only.py` and `Moment Frame - Lateral Load.py`.
- Change kwargs from `Direction` to `direction`.
- Fix render code in examples
- Due to commit 668e69279cd985a704b91c4e0303e3865039d304 , `render_model` is deprecated. So change it to `Rendered` class.
- Fix FEModel3D and Renderer attr in Examples
- `FEModel3D` does not have attr like `Quads` or `Meshes`, change it to `quads` and `meshes`, respectively.
- `Renderer` does not have attr `labels`, change it to `show_labels`.
Following the completion of the aforementioned fixes, all …
> Fix several bugs in Examples

- PyNite/FEModel3D.py
Some minor changes to the FEModel3D class for API consistency. Namely, `add_material` wasn't returning the new material name it had just created and the `add_section` methods didn't allow for automatic naming like the rest of the factory methods.
I have also added basic type annotations to the main user-facing methods of FEModel3D.
> API consistency + Type annotations

- .github/workflows/build-and-test.yml
- CONTRIBUTING.md
- requirements.txt
Add the `pytest` library for running tests as detailed in issue #255
* Update `requirements.txt` to included `pytest`
* Run tests in the test-and-build workflow with `pytest` instead of `unittest`
* Add instructions to `CONTRIBUTING.md` on how to run tests with `pytest`
Resolves #225
> Switch to pytest framework for testing

- Pynite/Analysis.py
- Pynite/BeamSegY.py
- Pynite/BeamSegZ.py
- Pynite/FEModel3D.py
- Pynite/FixedEndReactions.py
- Pynite/LoadCombo.py
- Pynite/Material.py
- Pynite/Member3D.py
- Pynite/Mesh.py
- Pynite/Node3D.py
- Pynite/PhysMember.py
- Pynite/Plate3D.py
- Pynite/Quad3D.py
- Pynite/Rendering.py
- Pynite/Reporting.py
- Pynite/Section.py
- Pynite/ShearWall.py
- Pynite/Spring3D.py
- Pynite/Tri3D.py
- Pynite/Visualization.py
This add type hints to almost all class and method functions throughout library. I tried to scope new type related imports under the `if TYPE_CHECKING:` flag to minimize actual runtime performance hits from additional imports.
There were a few places where the types were a little ambiguous (mostly on the internal methods), so the types might be narrowed too much. For example, the argument x might permit a list of floats inl ieu of just a single float. 
Also, I Left type errors that show up in the editor after defining types on things largely untouched to keep scope of this PR strictly to adding type hints to the code. Future PRs can address these kind of warnings. These warnings were good to be warned about and should probably be fixed at some point to prevent errors popping up later.
I …
> Added type hints throughout

- Pynite/Node3D.py
- Pynite/VTKWriter.py
This is my proposed correction for the faulty coordinate system I used in #254 
The following image shows the absolute membrane stresses with a downwards load at the end.
> Fixed error with Quad3D coordinate system in the VTKWriter

- Pynite/Rendering.py
**Problem:**
Users attempting to customize the PyVista `plotter` instance within `Pynite.Rendering.Renderer` (e.g., adding grids or origin axes using `plotter.show_grid()`) before calling `render_model()` find their additions are removed. This occurs because the internal `Renderer.update()` method clears the plotter (using self.plotter.clear()) before adding Pynite's standard visualization elements.
**Solution:**
This change introduces a simple callback mechanism:
1.  A new list attribute, `post_update_callbacks: List[Callable[[pv.Plotter], None]]`, is added to the `Renderer` class during initialization. The type hint clearly indicates that functions added to this list must accept a `pyvista.Plotter` object as their sole argument.
2.  At the end of the `Renderer.update()` method, after …
> Add post-update callback to Renderer for pv.Plotter (self.plotter) customization

- Testing/test_continuous_beam.py
Quickly implemented test to validate the results of the `FEModel3D.moment_array` method.
Will add additional tests for the other array methods which will be used to validate that `max(model.something_array(...)[1]) == model.max_something(...)` and `min(model.something_array(...)[1]) == model.min_something(...)`.
These tests are expected to fail on the current version of PyNite at the time this pull request was opened.
> test: added continuous beam test to check max moment results

- Pynite/__init__.py
Version is retrieved dynamically from the package after it is built by setup.py. This allows users to access the version of Pynite they have installed without @JWock82 having to manually update the version number in `__init__.py` whenever a new release is made.
Closes #273 
In the long-term, I recommend moving away from setup.py to pyproject.toml where the version and description of the package can be dynamically retrieved from the `__init__.py` file (making the `__init__.py` file the source of truth and the package being built according to those values). 
However, this is a quick fix that will allow users to easily check their Pynite version to aid in the diagnosis of potential incorrect values.
> feat: implement dynamic __version__
